### ISSUE TITLE
Reduce test output

### ISSUE THREAD

**Issue by AloisKraus** [Siemens-Healthineers/ETWAnalyzer#11]
Test output of unit tests is not really readable in Github Actions.
In case of green tests no output should be printed in the best case.
For starters we remove the longest console output from our test. 

- ETWAnalyzer\Commands\AnalyzeCommand.cs
  Remove PrintProcessBar method
- ETWAnalyzer\Analyzers\ScreenshotBitmapping\SampleBitmapGenerator.cs
  Remove void Print() method
- ETWAnalyzer\Analyzers\TestCount\TestCountAnalyzer.cs
  Remove public override void Print()
- ETWAnalyzer\Analyzers\TestCount\TestCountAnalyzer.cs 
  call public override void Print() only if test is exited with an Exception

**Comment by Tejesh-SH** [comment]
corrections implementing under branch [Tejesh-SH:reduce_test_output](https://github.com/Tejesh-SH/ETWAnalyzer/tree/reduce_test_output)
